<?php
// m#404 A token given to a customer to activate a licence at a later date
class Token {

    var $id;
    var $rootId;
    var $groupId;
    var $userId;
    var $email;
    var $serial;
    var $duration;
    var $productCode;
    var $productVersion;
    var $expiryDate;
    var $activationDate;
    var $activationMethod;

    const STATUS_AVAILABLE = 0;
    const STATUS_USED = 1;
    const STATUS_EXPIRED = 2;

    function Token($dbObj = null) {
        if ($dbObj)
            $this->fromDatabaseObj($dbObj);
    }
    /*
     * Take the information out of $obj (generated by AdoDB FetchNextObject()) and set the attributes of this object based on it
     *
     * @param obj The object returned for the record by FetchNextObject()
     */
    function fromDatabaseObj($obj, $db = null) {
        $this->id = $obj->F_TokenID;
        $this->rootId = $obj->F_RootID;;
        $this->groupId = $obj->F_GroupID;
        $this->userId = $obj->F_UserID;
        $this->email = $obj->F_Email;
        $this->serial = $obj->F_Serial;
        $this->duration = $obj->F_Duration;
        $this->productCode = $obj->F_ProductCode;
        $this->productVersion = $obj->F_ProductVersion;
        $this->expiryDate = $obj->F_ExpiryDate;
        $this->activationDate = $obj->F_ActivationDate;
        $this->activationMethod = $obj->F_ActivationMethod;
    }

}
