<?php
/*
 * Purpose: Hold data from T_SessionTrack used to track how a user is going through a program
 * Created by Adrian Raper.
 * Date: 10-Aug-17
 */

class SessionTrack {

    var $sessionId;
    var $userId;
    var $productCode;
    var $rootId;
    var $startDateStamp;
    var $lastUpdateDateStamp;
    var $duration;
    var $contentId;
    var $data;
    var $status;

    const STATUS_OPEN = 0;
    const STATUS_CLOSED = 1;
    const STATUS_DORMANT = 2;
    const STATUS_PURGE = 3;
    const MINIMUM_DURATION = 59;
    const THINKING_DURATION = 1800;

    function SessionTrack($dbObj = null) {
        if ($dbObj)
            $this->fromDatabaseObj($dbObj);
    }

    /*
     * Take the information out of $obj (generated by AdoDB FetchNextObject()) and set the attributes of this object based on it
     *
     * @param obj The object returned for the record by FetchNextObject()
     */
    function fromDatabaseObj($obj) {
        $this->sessionId = intval($obj->F_SessionID);
        $this->userId = intval($obj->F_UserID);
        $this->rootId = intval($obj->F_RootID);
        $this->productCode = intval($obj->F_ProductCode);
        if ($obj->F_StartDateStamp && strtotime($obj->F_StartDateStamp) > 0) $this->startDateStamp = $obj->F_StartDateStamp;
        if ($obj->F_LastUpdateDateStamp && strtotime($obj->F_LastUpdateDateStamp) > 0) $this->lastUpdateDateStamp = $obj->F_LastUpdateDateStamp;
        $this->duration = intval($obj->F_Duration);
        $this->contentId = $obj->F_ContentID;
        $this->data = ($obj->F_Data) ? json_decode($obj->F_Data, true) : null;
        $this->status = intval($obj->F_Status);
    }

    /**
     * Convert this object to an associative array ready to pass to AutoExecute
     */
    function toAssocArray() {
        $array = array();
        $array['F_SessionID'] = $this->sessionId;
        $array['F_UserID'] = $this->userId;
        $array['F_RootID'] = $this->rootId;
        $array['F_ProductCode'] = $this->productCode;
        $array['F_StartDateStamp'] = $this->startDateStamp;
        $array['F_LastUpdateDateStamp'] = $this->lastUpdateDateStamp;
        $array['F_Duration'] = $this->duration;
        $array['F_ContentID'] = $this->contentId;
        $array['F_Data'] = ($this->data) ? json_encode($this->data) : null;
        $array['F_Status'] = $this->status;
        return $array;
    }
    /*
     * Some helper functions to get and set specific named items from data
     */
    function getSeed() {
        return (isset($this->data["seed"])) ? $this->data["seed"] : null;
    }
    function setSeed($seed) {
        if (isset($seed))
            $this->data["seed"] = $seed;
    }
    function getResult() {
        return (isset($this->data["result"])) ? $this->data["result"] : null;
    }
    function setResult($result) {
        if (isset($result))
            $this->data["result"] = $result;
    }
}
