USE global_r2iv2;

-- For the people who are currently testing R2I - keep them in group 170 which we are shifting to the testing account (1)
UPDATE T_Membership
SET F_RootID = 1
WHERE F_GroupID = 170;

-- The Americas admin user needs to go back into the correct group and root
UPDATE T_Membership
SET F_RootID = 170, F_GroupID = 22156
WHERE F_UserID = 105;

DELETE FROM T_Groupstructure;
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (173,'Hong Kong portal','',22148);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (22155,'Rest of World','',22148);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (22148,'The British Council ORS','',22148);

INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (1,'Testing account','',1);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (170,'R2IV2 user testing','',1);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (22150,'Clarity','',1);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (22151,'Others','',1);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (22154,'BC Marketing','',1);

INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (100,'India','BC India',100);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (101,'BC Warsaw','Poland',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (102,'BC Pairs','France',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (107,'BC Hong Kong','Hong Kong',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (167,'The British Council AMESA','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (168,'The British Council SEAsia','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (169,'The British Council Europe','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (22156,'The British Council Americas','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (171,'China','China',171);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (172,'Malta Chamber of Commerce & Ent.','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (174,'Lund Folkuniversitetet','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (175,'BC Milan','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (176,'BC Turkey','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (177,'BC Slovenia','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (178,'BC Naples','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (180,'Göteborg Folkuniversitetet','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (181,'Baltic Council (BLTC)','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (182,'BC Hungary','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (183,'BC Lithuania','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (184,'BC Barcelona','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (185,'BC Austria','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (186,'Stockholm Folkuniversitetet','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (187,'BC Berlin','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (188,'Friundervisningen i  Bergen','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (189,'Tallinn University Language centre','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (190,'BC Lisbon','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (191,'BC Belgium','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (192,'BC Croatia','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (193,'BC Georgia','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (194,'BC Czech Republic','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (195,'Oslo, Folkeuniversitetet 1','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (196,'BC Athens','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (197,'BC Switzerland','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (198,'BC Bilbao','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (199,'BLTC','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (200,'BC Porto','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (201,'BC Macedonia','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (202,'BC Madrid','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (203,'BC Israel','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (204,'BC Bosnia and Herzegovina','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (205,'BC Albania','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (206,'EDU','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (207,'BC Ukraine','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (209,'BC Rome','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (210,'BC Krakow','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (211,'BC Cyprus','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (212,'BC Thessaloniki','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (213,'BC Serbia and Montenegro','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (214,'BC Romania','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (215,'BC Slovakia','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (216,'BC Azerbaijan','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (217,'BC Bulgaria','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (218,'BC Armenia','',169);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (219,'BC Venezuela (Trinidad & Tobago)','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (220,'Centro Anglo-Paraguayo','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (221,'BC Venezuela (Caracas)','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (222,'Cultura Inglesa Buenos Aires','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (223,'British Asociacion Cultural Peruano Britanico','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (224,'BC Colombia','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (225,'Instituto Cultural Anglo Uruguayo','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (226,'BC Sao Paulo','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (227,'Instituto Britanico Costa Rica','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (228,'BC Cuba','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (229,'Internat Lang Instit Halifax','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (230,'Conestoga College','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (231,'The Language Works','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (232,'Instituto Chileno','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (233,'BC Mexico','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (234,'BC Jamaica','',22156);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (235,'BC Uganda','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (236,'BC Yemen','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (237,'BC Islamabad','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (238,'BC Dubai','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (239,'BC Kandy','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (240,'BC Mozambique','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (241,'BC Sudan','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (242,'BC Nepal','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (243,'BC Yaounde','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (244,'BC Tunis','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (245,'BC Karachi','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (246,'BC Namibia','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (247,'BC New Delhi','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (248,'BC Kuwait','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (249,'BC Mauritius','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (250,'BC Libya','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (251,'BC Morocco','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (252,'BC Abu Dhabi','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (253,'BC Johannesburg','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (254,'BC Colombo','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (255,'BC Muscat','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (256,'BC Alexandria','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (257,'BC Al Khobar','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (258,'BC Qatar','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (259,'BC Bahrain','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (260,'BC Cairo','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (261,'BC Tanzania','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (262,'BC Syria','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (263,'BC Peshawar','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (264,'BC Bangladesh ','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (265,'BC Senegal','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (266,'BC Lahore','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (267,'BC Zambia','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (268,'BC Ghana','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (269,'BC Cape Town','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (270,'BC Mumbai','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (271,'BC Eritria','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (272,'BC Uzbekistan','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (273,'BC Riyadh','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (274,'BC Lebanon','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (275,'BC Nigeria','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (276,'BC Kazakhistan','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (277,'BC Palestinian Territories','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (278,'BC Jeddah','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (279,'BC Chennai','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (280,'BC Kolkata','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (281,'BC Jordan','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (282,'BC Zimbabwe','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (283,'BC Nairobi','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (284,'BC Ethiopia','',167);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (286,'MIT','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (287,'BC Sabah','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (288,'BC Penang','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (289,'BC Osaka','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (290,'BC Taipei','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (291,'Eastern Institute of Technology','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (292,'BC Shanghai','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (293,'BC Manila','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (294,'BC Korea','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (295,'BC Guangzhou','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (296,'BC Beijing & Ulaanbaatar, Mongolia','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (297,'BC HCMC','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (298,'BC Tokyo','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (299,'BC KL','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (300,'BC Sarawak','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (301,'CFBT Brunei','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (302,'BC Chongqing','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (303,'BC Hanoi','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (304,'BC Rangoon','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (305,'BC Singapore','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (306,'BC Chiang Mai','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (307,'BC Kaohsiung','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (308,'BC Bangkok','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (309,'BC Philippines','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (310,'BC Kuala Lumpur','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (311,'Brunei','',168);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (312,'The British Council Anonymous','',312);
INSERT INTO `T_Groupstructure` (`F_GroupID`,`F_GroupName`,`F_GroupDescription`,`F_GroupParent`) VALUES (313,'BC Malawi','',167);
