<?php

class ImportXMLParser {
	
	var $doc;
	
	/**
	 * Given a XML document (generated by ExportXML.php) recreate an array of manageables ready for re-insertion into the database.
	 */
	function xmlToManageables($doc) {
		$this->doc = $doc;
		
		$manageables = array();
		
		$xPath = new DOMXPath($this->doc);
		foreach ($xPath->query("*", $doc->documentElement) as $node)
			$manageables[] = $this->createManageable($node, $this->doc);
		
		return $manageables;
	}
	
	private function recurse($node, $context) {
		$xPath = new DOMXPath($this->doc);
		
		$result = array();
		
		foreach ($xPath->query("*", $context) as $node)
			$result[] = $this->createManageable($node);
		
		return $result;
	}
	
	private function createManageable($node) {
		switch ($node->nodeName) {
			case "group":
				$group = Group::createFromXML($node);
				$group->manageables = $this->recurse($node, $node);
				return $group;
			case "user":
				return User::createFromXML($node);
		}
	}

}

?>
