<?php
/*
 * Created by Adrian Raper.
 * User: Adrian
 * Date: 10-Aug-17
 */

class ContextSession {

    var $sessionId;
    var $userId;
    var $rootId;
    var $productCode;
    var $startDateStamp;

    function ContextSession($dbObj = null) {
        if ($dbObj)
            $this->fromDatabaseObj($dbObj);
    }

    /*
     * Take the information out of $obj (generated by AdoDB FetchNextObject()) and set the attributes of this object based on it
     *
     * @param obj The object returned for the record by FetchNextObject()
     */
    function fromDatabaseObj($obj) {
        $this->sessionId = intval($obj->F_SessionID);
        $this->userId = intval($obj->F_UserID);
        $this->rootId = intval($obj->F_RootID);
        $this->productCode = intval($obj->F_ProductCode);
        if ($obj->F_StartDateStamp && strtotime($obj->F_StartDateStamp) > 0) $this->startDateStamp = $obj->F_StartDateStamp;
    }

    /**
     * Convert this object to an associative array ready to pass to AutoExecute
     *
     * @param for_update If this array is destined for an update AutoExecute don't include the identity column as this breaks MSSQL
     */
    function toAssocArray() {
        $array = array();
        $array['F_SessionID'] = $this->sessionId;
        $array['F_UserID'] = $this->userId;
        $array['F_RootID'] = $this->rootId;
        $array['F_ProductCode'] = $this->productCode;
        $array['F_StartDateStamp'] = $this->startDateStamp;
        return $array;
    }

}
